# Generated by Django 6.0.5 on 2026-05-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skill_category_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Fontend'), ('database', 'Database'), ('devops', 'DevOps'), ('tools', 'Tools'), ('python', 'Python'), ('djnago', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JAVASCRIPT'), ('drf', 'DRF'), ('git', 'GIT'), ('github', 'GITHUB'), ('flashpost/postman', 'FLASHPOST/POSTMAN'), ('postgresql', 'POSTGRESQL'), ('other', 'Other')], default='backend', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Fontend'), ('database', 'Database'), ('devops', 'DevOps'), ('tools', 'Tools'), ('python', 'Python'), ('djnago', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JAVASCRIPT'), ('drf', 'DRF'), ('git', 'GIT'), ('github', 'GITHUB'), ('flashpost/postman', 'FLASHPOST/POSTMAN'), ('postgresql', 'POSTGRESQL'), ('other', 'Other')], default='backend', max_length=50),
        ),
    ]
